apiVersion: v1
kind: Service
metadata:
  name: rentflow
  labels:
    app: rentflow
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: rentflow
