// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const PLACEHOLDER_ENV =
  SUPABASE_URL === "https://example.supabase.co" ||
  SUPABASE_PUBLISHABLE_KEY === "ci-placeholder-anon-key";
const MISSING_ENV = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || PLACEHOLDER_ENV;
if (MISSING_ENV) {
  console.warn(
    '%c[RentFlow] Missing Supabase env vars (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY).\n' +
    '  The app will load but auth and data features will be unavailable.\n' +
    '  Copy .env.example to .env.local and fill in your Supabase project values.',
    'color: #eab308; font-weight: bold'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage: Storage = {
  getItem: (k: string) => { try { return localStorage.getItem(k); } catch { return null; } },
  setItem: (k: string, v: string) => { try { localStorage.setItem(k, v); } catch {} },
  removeItem: (k: string) => { try { localStorage.removeItem(k); } catch {} },
  get length() { try { return localStorage.length; } catch { return 0; } },
  key: (i: number) => { try { return localStorage.key(i); } catch { return null; } },
  clear: () => { try { localStorage.clear(); } catch {} },
};

function createNoopProxy(): ReturnType<typeof createClient<Database>> {
  const noopAuth = {
    onAuthStateChange: () => ({
      data: {
        subscription: {
          unsubscribe: () => {},
        },
      },
    }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    resetPasswordForEmail: () => Promise.resolve({ data: {}, error: { message: "Supabase is not configured" } }),
    setSession: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    signOut: () => Promise.resolve({ error: null }),
    updateUser: () => Promise.resolve({ data: { user: null }, error: { message: "Supabase is not configured" } }),
  };
  interface NoopBuilder extends PromiseLike<{ data: never[]; error: null }> {
    select(...args: unknown[]): NoopBuilder;
    insert(...args: unknown[]): NoopBuilder;
    update(...args: unknown[]): NoopBuilder;
    upsert(...args: unknown[]): NoopBuilder;
    delete(...args: unknown[]): NoopBuilder;
    eq(...args: unknown[]): NoopBuilder;
    neq(...args: unknown[]): NoopBuilder;
    gt(...args: unknown[]): NoopBuilder;
    gte(...args: unknown[]): NoopBuilder;
    lt(...args: unknown[]): NoopBuilder;
    lte(...args: unknown[]): NoopBuilder;
    like(...args: unknown[]): NoopBuilder;
    ilike(...args: unknown[]): NoopBuilder;
    is(...args: unknown[]): NoopBuilder;
    in(...args: unknown[]): NoopBuilder;
    contains(...args: unknown[]): NoopBuilder;
    containedBy(...args: unknown[]): NoopBuilder;
    range(...args: unknown[]): NoopBuilder;
    textSearch(...args: unknown[]): NoopBuilder;
    not(...args: unknown[]): NoopBuilder;
    or(...args: unknown[]): NoopBuilder;
    and(...args: unknown[]): NoopBuilder;
    filter(...args: unknown[]): NoopBuilder;
    match(...args: unknown[]): NoopBuilder;
    order(...args: unknown[]): NoopBuilder;
    limit(...args: unknown[]): NoopBuilder;
    single(...args: unknown[]): NoopBuilder;
    maybeSingle(...args: unknown[]): NoopBuilder;
    csv(...args: unknown[]): NoopBuilder;
    returns(...args: unknown[]): NoopBuilder;
    throwOnError(...args: unknown[]): NoopBuilder;
    abortSignal(...args: unknown[]): NoopBuilder;
  }

  // Chainable noop query builder — every method returns `this`, and
  // when awaited it resolves to { data: [], error: null }.
  function createNoopBuilder(): NoopBuilder {
    const builder: NoopBuilder = {
      then<R>(resolve: (value: { data: never[]; error: null }) => R) { return Promise.resolve({ data: [], error: null }).then(resolve); },
      catch<R>(fn: (reason: unknown) => R) { return Promise.resolve({ data: [], error: null }).catch(fn); },
    } as NoopBuilder;
    const chainMethods = [
      'select', 'insert', 'update', 'upsert', 'delete',
      'eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike',
      'is', 'in', 'contains', 'containedBy', 'range', 'textSearch',
      'not', 'or', 'and', 'filter', 'match',
      'order', 'limit', 'single', 'maybeSingle',
      'csv', 'returns', 'throwOnError', 'abortSignal',
    ];
    for (const m of chainMethods) {
      builder[m] = () => builder;
    }
    return builder;
  }

  const noop = new Proxy({}, {
    get(_target, prop) {
      if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
      if (prop === 'auth') return noopAuth;
      if (prop === 'from' || prop === 'rpc' || prop === 'storage') {
        return () => createNoopBuilder();
      }
      if (prop === 'channel') {
        return () => ({
          on: () => ({ subscribe: () => ({}) }),
          subscribe: () => ({}),
          unsubscribe: () => {},
        });
      }
      return typeof prop === 'string'
        ? () => createNoopBuilder()
        : noop;
    },
  });
  return noop as unknown as ReturnType<typeof createClient<Database>>;
}

export const supabase = MISSING_ENV
  ? createNoopProxy()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      }
    });
